name: C and Python coverage

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'

  pull_request:
    branches: [develop]
    types: [opened]
    paths-ignore:
      - 'docs/**'
      - '**.md'

  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running workflow'
        required: true

jobs:
  coverage:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Log reason (manual run only)
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Reason for triggering: ${{ github.event.inputs.reason }}"

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Build and install AFDKO wheel
      env:
        XFLAGS: '--coverage'
      run: |
        git config --global url.https://github.com/.insteadOf git://github.com/
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt -r requirements-dev.txt
        python -m pip install build>=0.7.0
        python -m build --wheel
        echo 'Installing AFDKO wheel...'
        python -m pip install dist/*.whl -q
        
    - name: Generate and upload Python and C coverage
      run: |
        python -m pip install pytest-cov
        python -m pytest tests --cov --cov-report=xml
        bash <(curl -s https://codecov.io/bash) -y .codecov.yml
